### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by hettlage** [saltastroops/data-archive-frontend#147]
Depending on the screen size there are some GUI issues, see screenshots.

<img width="315" alt="screenshot_405" src="https://user-images.githubusercontent.com/11633365/74429560-e2adef00-4e63-11ea-888a-cb69f647d876.png">

<img width="455" alt="screenshot_404" src="https://user-images.githubusercontent.com/11633365/74429639-0709cb80-4e64-11ea-8e22-e34e047857b9.png">

**Comment by hettlage** [comment]
Another one, on the cart. The space between checkboxes and buttons should be larger.

<img width="471" alt="screenshot_406" src="https://user-images.githubusercontent.com/11633365/74444357-6cb68180-4e7d-11ea-846f-45d3e00479b1.png">

**Comment by Eb-Zeero** [comment]
on what branch are you having the second issue. I believe it is not yet on development branch.
